// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetFileInfo(arg1:string):Promise<main.DirectoryItem>;

export function ListDirectory(arg1:string):Promise<Array<main.DirectoryItem>>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ReadFileContents(arg1:string):Promise<string>;
